const foods = [
    {
      id: '1',
      name: 'Jolly Spaghetti',
      includings: '1 pc. Jolly Spaghetti with 1 glass of Coca Cola',
      price: '1.10',
      image: require('../assets/jollySpaghetti.png'),
    },
    {
      id: '2',
      name: 'Chickenjoy with rice and Coke',
      includings: '1pc Chickenjoy, 1pc rice, and 1 Coke',
      price: '1.80',
      image: require('../assets/chickenjoyRice.png'),
    },
    {
      id: '3',
      name: 'Yumburger',
      includings: '1pc Yumburger',
      price: '0.60',
      image: require('../assets/yumburger-1.png'),
    },
    {
      id: '4',
      name: 'Chickenjoy with Fries and Rice',
      includings: '1pc Chickenjoy with 1pc Rice, 1 Regular Fries and 1 Coke',
      price: '1.80',
      image: require('../assets/chickenjoyRiceFries.png'),
    },
    {
        id: '5',
        name: 'McSpaghetti',
        includings: '1pc McSpaghetti and 1 Coke',
        price: '1.10',
        image: require('../assets/mcspaghetti.png'),
    },
    {
        id: '6',
        name: 'McBurger',
        includings: '1pc McBurger',
        price: '0.60',
        image: require('../assets/mcburger.png'),
    },
    {
        id: '7',
        name: 'McChicken',
        includings: '1pc McChicken with Rice and 1 Coke',
        price: '1.85',
        image: require('../assets/mcchicken.png'),
    },
    {
        id: '8',
        name: 'McSpaghetti with Fries and Coke',
        includings: '1pc McSpaghetti, 1 Regular Fries, and 1 Coke',
        price: '1.70',
        image: require('../assets/mcSpaghettiFries.png'),
    },
    {
        id: '9',
        name: 'Pecho Large',
        includings: '1pc Inasal Pecho Large with Rice',
        price: '2.10',
        image: require('../assets/pechoLarge.png'),
    },
    {
        id: '10',
        name: 'PM1',
        includings: '1pc Paa Regular Size with Rice',
        price: '1.90',
        image: require('../assets/pm1.png'),
    },
    {
        id: '11',
        name: 'Pork Sisig',
        includings: '1 Pork Sisig with Rice and 1 Coke',
        price: '1.80',
        image: require('../assets/porkSisig.png'),
    },
    {
        id: '12',
        name: '1-Stick Pork Bbq with Rice and Coke',
        includings: '1stick Pork Bbq, 1pc Rice, and Coke',
        price: '1.10',
        image: require('../assets/sm2.png'),
    },
    {
        id: '13',
        name: 'Chinese Style Fried Chicken',
        includings: '1pc Chinese Style Fried Chicken, 1pc Rice, and Coke',
        price: '1.70',
        image: require('../assets/1pcChineseStyleFriedChicken.png'),
    },
    {
        id: '14',
        name: 'Sweet and Sour Fish',
        includings: '1 Sweet and Sour Fish, 1pc Rice, and coke',
        price: '1.90',
        image: require('../assets/sweetAndSourFish.png'),
    },
    {
        id: '15',
        name: 'Sweet and Sour Chicken',
        includings: '1 Sweet and Sour Chicken, 1pc Rice, and coke',
        price: '1.90',
        image: require('../assets/sweetAndSourChicken.png'),
    },
    {
        id: '16',
        name: 'Sweet and Sour Pork',
        includings: '1 Sweet and Sour Pork, 1pc Rice, and coke',
        price: '1.90',
        image: require('../assets/sweetAndSourPork.png'),
    },
  ];
  
  export default foods;